# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_O8iy6Adqnrzdfu4i6etSadOFQvs2fL8
"""

from sklearn.neighbors import NearestNeighbors
import numpy as np
import matplotlib.pyplot as plt

# Generating sample data
np.random.seed(42)
X = 0.3 * np.random.randn(100, 2)
X_outliers = np.random.uniform(low=-4, high=4, size=(20, 2))
X = np.r_[X + 2, X - 2, X_outliers]

print(X)

# Fit the nearest neighbors model
k = 10  # Number of neighbors
knn = NearestNeighbors(n_neighbors=k)
knn.fit(X)

# Calculate distances to k-th nearest neighbors for each point
distances, _ = knn.kneighbors(X)
kth_distance = distances[:, -1]
# Set threshold for outlier detection
threshold = np.percentile(kth_distance, 95)  # Adjust the percentile based on your data
# Detect outliers
outlier_indices = np.where(kth_distance > threshold)[0]
outliers = X[outlier_indices]

# Plot the results
plt.figure(figsize=(12, 8))
plt.scatter(X[:, 0], X[:, 1], color='k', s=30, label="Data points")
plt.scatter(outliers[:, 0], outliers[:, 1], marker='o',
            edgecolors='r', facecolors='none', s=100, label="Outliers")
plt.title('Outlier Detection using KNN')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.show()

import pandas as pd
df_customer = pd.read_csv('customer.csv')
display(df_customer.head())
display(df_customer.info())

display(outliers_customer)

from sklearn.preprocessing import StandardScaler

# Select the relevant features for outlier detection
X_customer = df_customer[['Annual_Income', 'Spending_Score']]

# Scale the data using StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_customer)

# Fit the nearest neighbors model to the scaled data
k_customer = 5  # You can adjust this value, typically between 2 and 50
knn_customer = NearestNeighbors(n_neighbors=k_customer)
knn_customer.fit(X_scaled)

# Calculate distances to k-th nearest neighbors for each point
distances_customer, _ = knn_customer.kneighbors(X_scaled)
kth_distance_customer = distances_customer[:, -1]

# Set threshold for outlier detection (e.g., 90th percentile)
threshold_customer = np.percentile(kth_distance_customer, 90) # Adjust this percentile as needed

# Detect outliers
outlier_indices_customer = np.where(kth_distance_customer > threshold_customer)[0]
outliers_customer = X_customer.iloc[outlier_indices_customer]

# Plot the results
plt.figure(figsize=(10, 7))
plt.scatter(X_customer['Annual_Income'], X_customer['Spending_Score'], color='k', s=50, label='Data points')
plt.scatter(outliers_customer['Annual_Income'], outliers_customer['Spending_Score'],
            marker='o', edgecolors='r', facecolors='none', s=150, label='Outliers')
plt.title('Outlier Detection using KNN on Customer Data (Annual Income vs Spending Score)')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.legend()
plt.grid(True)
plt.show()

