# -*- coding: utf-8 -*-
"""t-test_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEeaGSyhb1WL_g2iCyj33LbguxW8Zgmh
"""

# Exercise 1:

import pandas as pd
from scipy import stats

data = {
    "Test_Case": ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8"],
    "Response_Time_Before": [420, 450, 410, 470, 440, 460, 430, 445],
    "Response_Time_After": [360, 390, 355, 400, 380, 395, 370, 385]
}

df = pd.DataFrame(data)
df

Two_Sample_Results1=stats.ttest_rel(
    df["Response_Time_Before"],
    df["Response_Time_After"]
)
Two_Sample_Results1

"""Since the t-calc = 39.08 is greater than the t-table = 2.365 and the p-value is less than α = 0.05, the result is statistically significant."""

# Exercise 2:

import pandas as pd
from scipy import stats

data = {
    "Household_ID": ["H1","H2","H3","H4","H5","H6","H7","H8","H9","H10"],
    "Daily_Energy_Consumption": [11.2, 10.8, 11.5, 10.6, 11.0, 11.3, 10.9, 11.1, 10.7, 11.4]
}

df = pd.DataFrame(data)
df

one_sample_result=stats.ttest_1samp(
    df["Daily_Energy_Consumption"],
    11
)
one_sample_result

"""Since t-calc = 0.52 is less than t-table = 2.262, and the p-value is greater than α = 0.05, the result is not statistically significant.
Hence, the null hypothesis is accepted and the alternative hypothesis is rejected.
"""