# -*- coding: utf-8 -*-
"""smote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6O1e3oYeK41a4wXiv65XoBvjETFz18v
"""

import pandas as pd
import pandas as pd
import seaborn as sns

dataset = pd.read_excel(r'Admission_St.xlsx')
dataset

X = dataset.iloc[:,1:4]
Y = dataset.iloc[:,0:1]
Y.value_counts()

dataset.describe()

sns.countplot(x="Admit", data=dataset)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3, random_state=0)

len(X_train)

len(Y_train)

len(X_test)

len(Y_test)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, roc_auc_score, precision_score, recall_score, f1_score
model = LogisticRegression(max_iter=5000)
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

acc1 = accuracy_score(Y_test, y_pred)
prec1 = precision_score(Y_test, y_pred)
rec1 = recall_score(Y_test, y_pred)
f11 = f1_score(Y_test, y_pred)

print("Before SMOTE")
print("Accuracy:", acc1)
print("Precision:", prec1)
print("Recall:", rec1)
print("F1 Score:", f11)
print("Classification report:\n", classification_report(Y_test, y_pred))

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_ros, Y_ros = ros.fit_resample(X_train, Y_train)

len(X_ros)

Y_ros.value_counts()

from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=0)
X_rus, Y_rus = rus.fit_resample(X_train, Y_train)

Y_rus.value_counts()

from imblearn.over_sampling import SMOTE
X_smote, Y_smote = SMOTE(k_neighbors=3).fit_resample(X_train, Y_train)

Y_smote.value_counts()

from sklearn.linear_model import LogisticRegression

log_model_smote = LogisticRegression()
log_model_smote.fit(X_smote, Y_smote)

y_pred_smote = log_model_smote.predict(X_test)
y_prob_smote = log_model_smote.predict_proba(X_test)[:,1]

acc2 = accuracy_score(Y_test, y_pred_smote)
prec2 = precision_score(Y_test, y_pred_smote)
rec2 = recall_score(Y_test, y_pred_smote)
f12 = f1_score(Y_test, y_pred_smote)

print("After SMOTE")
print("Accuracy:", acc2)
print("Precision:", prec2)
print("Recall:", rec2)
print("F1 Score:", f12)
print("Classification report:\n", classification_report(Y_test, y_pred_smote))

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
import numpy as np

# Prepare true labels for class 0 (treating it as the positive class for its own ROC)
Y_test_class0_binary = (Y_test['Admit'] == 0).astype(int)
# For class 1, the original Y_test (which has 0s and 1s) is already suitable
Y_test_class1_binary = Y_test['Admit']

# --- Before SMOTE ---
# Probabilities for Class 0 before SMOTE
y_prob_before_class0 = model.predict_proba(X_test)[:,0]
# Probabilities for Class 1 before SMOTE (this is y_prob from previous steps)
y_prob_before_class1 = y_prob

# ROC for Class 1 (Admit=1) before SMOTE
fpr_before_class1, tpr_before_class1, _ = roc_curve(Y_test_class1_binary, y_prob_before_class1)
roc_auc_before_class1 = auc(fpr_before_class1, tpr_before_class1)

# ROC for Class 0 (Admit=0) before SMOTE
fpr_before_class0, tpr_before_class0, _ = roc_curve(Y_test_class0_binary, y_prob_before_class0)
roc_auc_before_class0 = auc(fpr_before_class0, tpr_before_class0)

# --- After SMOTE ---
# Probabilities for Class 0 after SMOTE
y_prob_after_class0 = log_model_smote.predict_proba(X_test)[:,0]
# Probabilities for Class 1 after SMOTE (this is y_prob_smote from previous steps)
y_prob_after_class1 = y_prob_smote

# ROC for Class 1 (Admit=1) after SMOTE
fpr_after_class1, tpr_after_class1, _ = roc_curve(Y_test_class1_binary, y_prob_after_class1)
roc_auc_after_class1 = auc(fpr_after_class1, tpr_after_class1)

# ROC for Class 0 (Admit=0) after SMOTE
fpr_after_class0, tpr_after_class0, _ = roc_curve(Y_test_class0_binary, y_prob_after_class0)
roc_auc_after_class0 = auc(fpr_after_class0, tpr_after_class0)

# --- Plotting all four ROC AUC curves ---
plt.figure(figsize=(12, 8))

plt.plot(fpr_before_class1, tpr_before_class1, color='blue', linestyle='-',
         label=f'Before SMOTE (Class 1) (AUC = {roc_auc_before_class1:.4f})')
plt.plot(fpr_before_class0, tpr_before_class0, color='cyan', linestyle='--',
         label=f'Before SMOTE (Class 0) (AUC = {roc_auc_before_class0:.4f})')

plt.plot(fpr_after_class1, tpr_after_class1, color='red', linestyle='-',
         label=f'After SMOTE (Class 1) (AUC = {roc_auc_after_class1:.4f})')
plt.plot(fpr_after_class0, tpr_after_class0, color='magenta', linestyle='--',
         label=f'After SMOTE (Class 0) (AUC = {roc_auc_after_class0:.4f})')

plt.plot([0, 1], [0, 1], color='green', linestyle=':', label='Random Classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison for Each Class Before and After SMOTE')
plt.legend()
plt.grid(True)
plt.show()

print(f"\nAUC Score Before SMOTE (Class 1): {roc_auc_before_class1:.4f}")
print(f"AUC Score Before SMOTE (Class 0): {roc_auc_before_class0:.4f}")
print(f"AUC Score After SMOTE (Class 1): {roc_auc_after_class1:.4f}")
print(f"AUC Score After SMOTE (Class 0): {roc_auc_after_class0:.4f}")