# -*- coding: utf-8 -*-
"""visualization_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LbFhIHj782bpgxMOPQpRN96-4B7K1eq2

Exercise 1: Visualization-Based Analysis of the Titanic Dataset
"""

import seaborn as sns
import matplotlib.pyplot as plt

titanic = sns.load_dataset('titanic')

#1. Frequency distribution of categorical variables
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
sns.countplot(data=titanic, x='sex', ax=axes[0], palette='pastel')
sns.countplot(data=titanic, x='class', ax=axes[1], palette='muted')
sns.countplot(data=titanic, x='embark_town', ax=axes[2], palette='deep')
plt.suptitle('Frequency Distribution of Categorical Variables')
plt.show()

# 2. Distribution of numerical variables (Age and Fare)
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(titanic['age'].dropna(), kde=True, color='blue')
plt.title('Distribution of Age')
plt.subplot(1, 2, 2)
sns.histplot(titanic['fare'], kde=True, color='green')
plt.title('Distribution of Fare')
plt.show()

# 3. Relationship between passenger class and fare
plt.figure(figsize=(8, 6))
sns.boxplot(data=titanic, x='class', y='fare', palette='Set2')
plt.title('Passenger Class vs Fare')
plt.ylim(0, 300)
plt.show()

# 4. Survival rates with respect to gender and class
sns.catplot(data=titanic, x='class', hue='sex', y='survived', kind='bar', palette='magma')
plt.title('Survival Rate by Class and Gender')
plt.show()

"""Exercise 2: Visualization-Based Analysis of the Penguins Dataset"""

penguins = sns.load_dataset('penguins')

# 1. Distribution of numerical attributes
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
sns.histplot(data=penguins, x='bill_length_mm', kde=True, ax=axes[0], color='orange')
sns.histplot(data=penguins, x='bill_depth_mm', kde=True, ax=axes[1], color='red')
sns.histplot(data=penguins, x='body_mass_g', kde=True, ax=axes[2], color='purple')
plt.suptitle('Distribution of Physical Attributes')
plt.show()

# 2. Compare physical characteristics across species and sex
plt.figure(figsize=(10, 6))
sns.violinplot(data=penguins, x='species', y='body_mass_g', hue='sex', split=True, palette='Set1')
plt.title('Body Mass by Species and Sex')
plt.show()

# 3. Relationship between flipper length and body mass (Relational Plot)
sns.relplot(data=penguins, x='flipper_length_mm', y='body_mass_g', hue='species', style='sex', height=6)
plt.title('Flipper Length vs Body Mass')
plt.show()

# 4. Multivariate visualization (Pairplot)
sns.pairplot(penguins, hue='species', corner=True)
plt.show()