# -*- coding: utf-8 -*-
"""descriptive_statistical_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD5aJAGeFReLHa6dOuD4J711_HQ9Ej1d
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_excel('/content/Party_Data.xlsx')

df['Time'].describe()

m=df['Time'].mean()
print(m)

med=df['Time'].median()
print(med)

mode=df['Time'].mode()
print(mode)

harmean=stats.hmean(df['Time'])
print(harmean)

m1=df['Time'].max()
m2=df['Time'].min()

range=m1-m2
print(range)

q3=df['Time'].quantile(0.75)
q1=df['Time'].quantile(0.25)

iqr=q3-q1
print(iqr)

df.boxplot(['Time'])

s=df['Time'].std()
print(s)

v=df['Time'].var()
print(v)

cv=s/m
print(cv)

dq=harmean/m
print(dq)

skew=df['Time'].skew()
print(skew)

kurtosis=df['Time'].kurtosis()
print(kurtosis)

zscore=stats.zscore(df['Time'])
print(zscore)

#Conclusion:

# Mean is the average value of the data
# Median is the middle value of the data when arranged in order
# Mode is the value that occurs most frequently in the data
# Harmonic mean is the average used for rates or ratios, giving more weight to smaller values
# Geometric mean is the average that represents the central value of data that grows or changes multiplicatively
# Range is the difference between the highest and lowest values in the data
# Standard deviation shows how much the data values typically deviate from the mean
# Coefficient of variation measures relative variability by comparing the standard deviation to the mean
# Data Quality gives the consistency or reliability of the data values
# Skewness describes whether the data is tilted more to the left or right side
# Kurtosis shows how peaked or flat the data distribution is compared to a normal distribution