# -*- coding: utf-8 -*-
"""time_series_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OaDDbCtkEhRNSpXT_8dWeT9IOCUPeKO

Exercise 1
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose

series2 = pd.read_csv('retail.csv', header=0, index_col=0)
series2.plot()
pyplot.show()

result2 = seasonal_decompose(series2, model='multiplicative', period=1)
result2.plot()
pyplot.show()

"""Exercise 2"""

product = {'month': [1,2,3,4,5,6,7,8,9,10,11,12], 'demand': [250,235,200,260,279,300,310,305,350,316,350,290]}

df = pd.DataFrame(product)

from statsmodels.tsa.holtwinters import SimpleExpSmoothing

df['month'] = pd.date_range(start='2023-01-01', periods=12, freq='M')
df.set_index('month', inplace=True)

model = SimpleExpSmoothing(df['demand'], initialization_method='estimated')
model_fit = model.fit(smoothing_level=0.3, optimized=False)
df['SES_fit'] = model_fit.fittedvalues

forecast = model_fit.forecast(3)

print("Forecasted for next 3 months:")
print(forecast)

df['demand'].plot(label='Original')
df['SES_fit'].plot(label='Smoothed')
forecast.plot(label='Forecast')
plt.legend()
plt.show()